on:
  workflow_dispatch:
    inputs:
      artifact_s3_uri:
        required: true
        description: url of the artifact to deploy
        type: text
      environment:
        description: Environment to deploy
        type: choice
        required: true
        options:
          - dev
          - qa
          - prod

jobs:
  cd-job:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      ENVIRONMENT: ${{ inputs.environment }}
    steps:
      - name: set node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: install railwaicli
        run: | 
          node --version
          npm i -g @railway/cli
          railway --version
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: download artifact
        run: |
          aws s3 cp ${{ inputs.artifact_s3_uri }} .
      - name: unzip artifact
        run: unzip *.zip && rm *.zip
      - name: deploy to railway
        run: railway up
        env:
            RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROJECT_TOKEN }}
      

        

